# Site settings
title: 
header-img: img/home-bg.png
email: erinb0317@hotmail.com
copyright_name: e-be-walk
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  e-be-walk
learn_profile: e-be-walk
email_username: erinb0317@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
